// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUCSonw3_nUIzQkX66f6hTadj8d5SOpfM',
    appId: '1:1035518192236:web:51b6ca9192f76224dcc649',
    messagingSenderId: '1035518192236',
    projectId: 'finance-management-a0de9',
    authDomain: 'finance-management-a0de9.firebaseapp.com',
    storageBucket: 'finance-management-a0de9.appspot.com',
    measurementId: 'G-MHM08BL7RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnh-C5BuQ5L47tERXhGQ_G99PJibGbpDw',
    appId: '1:1035518192236:android:353b2d79d635d4dadcc649',
    messagingSenderId: '1035518192236',
    projectId: 'finance-management-a0de9',
    storageBucket: 'finance-management-a0de9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZjJCyOyrR6Z_7Fh-SLyQO3JcbNs79zVE',
    appId: '1:1035518192236:ios:30812c061686c31cdcc649',
    messagingSenderId: '1035518192236',
    projectId: 'finance-management-a0de9',
    storageBucket: 'finance-management-a0de9.appspot.com',
    iosBundleId: 'com.example.monneyManagement',
  );
}
